### PR TITLE
cover situation when there is no included tests the Feature https://g…

### PR DESCRIPTION
**Pull request by SiarheiDubovik**
…ithub.com/reportportal/agent-java-cucumber/issues/21

### CODE REVIEW

**Comment by DzmitryHumianiuk** [comment]
fix for #21

**Comment by evgenytkachenko** [comment]
@DzmitryHumianiuk I reproduced this Issue using https://github.com/reportportal/agent-java-cucumber4 
Can this fix be applied to that repo too ?

**Comment by DzmitryHumianiuk** [comment]
@evgenytkachenko looks like it is already merged.

**Comment by evgenytkachenko** [comment]
@DzmitryHumianiuk @HardNorth
I do not see thise changes in agent-java-cucumber4 , can we apply those changes to agent-java-cucumber4?
https://github.com/reportportal/agent-java-cucumber4/blob/master/src/main/java/com/epam/reportportal/cucumber/AbstractReporter.java

**Comment by evgenytkachenko** [comment]
@HardNorth can you please take a look at it ?

**Pull request merged**
